using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.NormalizedTextSnapshotRangeCollection.#System.Collections.Generic.IList`1<ActiproSoftware.Text.TextSnapshotRange>.RemoveAt(System.Int32)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "tagger", Scope = "resource", Target = "ActiproSoftware.Products.Text.Resources.resources")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.NormalizedTextSnapshotRangeCollection.#System.Collections.Generic.ICollection`1<ActiproSoftware.Text.TextSnapshotRange>.Remove(ActiproSoftware.Text.TextSnapshotRange)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.NormalizedTextSnapshotRangeCollection.#System.Collections.Generic.IList`1<ActiproSoftware.Text.TextSnapshotRange>.Insert(System.Int32,ActiproSoftware.Text.TextSnapshotRange)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Text.Tagging")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.Parsing.Implementation.AstNodeBase.#System.Collections.Generic.IEnumerable`1<ActiproSoftware.Text.Parsing.IAstNode>.GetEnumerator()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "ActiproSoftware.Text.Parsing.IAstNodeIdProvider")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Text.Tagging.Implementation")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.Parsing.Implementation.AstNodeBase.#System.Collections.IEnumerable.GetEnumerator()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.Implementation.CodeDocument.#ActiproSoftware.Text.Parsing.IParseTarget.UniqueId")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Lexer", Scope = "resource", Target = "ActiproSoftware.Products.Text.Resources.resources")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Lexing", Scope = "namespace", Target = "ActiproSoftware.Text.Lexing.Implementation")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ActiproSoftware.Text.Parsing.Implementation")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "lexer", Scope = "resource", Target = "ActiproSoftware.Products.Text.Resources.resources")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.NormalizedTextSnapshotRangeCollection.#System.Collections.Generic.ICollection`1<ActiproSoftware.Text.TextSnapshotRange>.Clear()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.NormalizedTextSnapshotRangeCollection.#System.Collections.Generic.ICollection`1<ActiproSoftware.Text.TextSnapshotRange>.IsReadOnly")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.Tagging.Implementation.CollectionTagger`1.#System.Collections.Generic.ICollection`1<ActiproSoftware.Text.Tagging.TagVersionRange`1<!0>>.IsReadOnly")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.NormalizedTextSnapshotRangeCollection.#System.Collections.Generic.ICollection`1<ActiproSoftware.Text.TextSnapshotRange>.Add(ActiproSoftware.Text.TextSnapshotRange)")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: AssemblyProduct("Text")]
[assembly: AssemblyCopyright("Copyright (c) 2007-2021 Actipro Software LLC.  All rights reserved.")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyInformationalVersion("21.1.0.0")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: InternalsVisibleTo("Text.Tests, PublicKey=0024000004800000940000000602000000240000525341310004000001000100cd030a14a47aab3d7bdafaa970d4b81f3e23ede5ccece89bf195ec44ba018463b8503df92d9f8c13ad9de265aa04c99876831acb7081c53ac26fd24235ddf9bd71cbc5a6790a6c0b871b4370c0521d185e793e3417834028a804c9cb71d3e114592d2cc4188a8afd1330556755ce8b336f18077408dee44542701633fe67a0b5")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ActiproSoftware.Text.Analysis.Implementation")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Text.Analysis.Implementation")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1812:AvoidUninstantiatedInternalClasses", Scope = "type", Target = "ActiproSoftware.Compatibility.StubToEnsureNamespaceIsValid")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Text.Analysis")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.Analysis.Implementation.StructureMatchResult.#ActiproSoftware.Text.ITextRangeProvider.TextRange")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Actipro Software LLC")]
[assembly: AssemblyTitle("Actipro Text/Parsing Library (for WPF)")]
[assembly: AssemblyDescription("A robust text/parsing framework for WPF.")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Text.Parsing")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Text.Implementation")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Text.Lexing")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Text.Parsing.Implementation")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Text.Exporters")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Text.Undo")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Outdent", Scope = "resource", Target = "ActiproSoftware.Products.Text.Resources.resources")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Text")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Text.Utility")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Text.RegularExpressions")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Text.Lexing.Implementation")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Text.Searching.Implementation")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Text.Searching")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.Lexing.Implementation.MergableLexerBase.#ActiproSoftware.Text.Lexing.IMergableLexer.LexicalStateIdProvider")]
[assembly: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "ActiproSoftware.Text.Lexing.ILexicalStateIdProvider")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.Lexing.Implementation.MergableLexerBase.#ActiproSoftware.Text.Lexing.ILexer.TokenIdProvider")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.Lexing.Implementation.MergableLexerBase.#ActiproSoftware.Text.Lexing.IMergableLexer.DefaultLexicalState")]
[assembly: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "ActiproSoftware.Text.Lexing.ITokenIdProvider")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "shapshot", Scope = "resource", Target = "ActiproSoftware.Products.Text.Resources.resources")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Lexing", Scope = "namespace", Target = "ActiproSoftware.Text.Lexing")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", MessageId = "whitespace", Scope = "resource", Target = "ActiproSoftware.Products.Text.Resources.resources")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", MessageId = "AutoCorrect", Scope = "resource", Target = "ActiproSoftware.Products.Text.Resources.resources")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ActiproSoftware.Text.Searching.Implementation")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.Lexing.Implementation.LexicalScopeBase.#ActiproSoftware.Text.Lexing.ILexicalScope.LexicalState")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", MessageId = "Flesch", Scope = "resource", Target = "ActiproSoftware.Products.Text.Resources.resources")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ActiproSoftware.Text.Exporters")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.Lexing.Implementation.LexicalScopeBase.#ActiproSoftware.Text.Lexing.ILexicalScope.ParentTransition")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.Lexing.Implementation.LexicalStateBase.#ActiproSoftware.Text.Lexing.ILexicalState.LexicalScopes")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.Lexing.Implementation.MergableLexerBase.#ActiproSoftware.Text.Utility.IKeyedObject.Key")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.Lexing.Implementation.LexicalStateBase.#ActiproSoftware.Text.Lexing.ILexicalState.ChildLexicalStates")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "ActiproSoftware.Text.Lexing.Implementation.LexicalStateBase.#ActiproSoftware.Text.Lexing.ILexicalState.Lexer")]
[assembly: AssemblyVersion("21.1.0.0")]
