using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_SCRIPT_DIALOG_KIND")]
public enum COREWEBVIEW2_SCRIPT_DIALOG_KIND
{
	COREWEBVIEW2_SCRIPT_DIALOG_KIND_ALERT,
	COREWEBVIEW2_SCRIPT_DIALOG_KIND_CONFIRM,
	COREWEBVIEW2_SCRIPT_DIALOG_KIND_PROMPT,
	COREWEBVIEW2_SCRIPT_DIALOG_KIND_BEFOREUNLOAD
}
