using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_PROCESS_KIND")]
public enum COREWEBVIEW2_PROCESS_KIND
{
	COREWEBVIEW2_PROCESS_KIND_BROWSER,
	COREWEBVIEW2_PROCESS_KIND_RENDERER,
	COREWEBVIEW2_PROCESS_KIND_UTILITY,
	COREWEBVIEW2_PROCESS_KIND_SANDBOX_HELPER,
	COREWEBVIEW2_PROCESS_KIND_GPU,
	COREWEBVIEW2_PROCESS_KIND_PPAPI_PLUGIN,
	COREWEBVIEW2_PROCESS_KIND_PPAPI_BROKER
}
