using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND")]
public enum COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND
{
	COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_PAGE,
	COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_IMAGE,
	COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_SELECTED_TEXT,
	COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_AUDIO,
	COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_VIDEO
}
