using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_MOUSE_EVENT_KIND")]
public enum COREWEBVIEW2_MOUSE_EVENT_KIND
{
	COREWEBVIEW2_MOUSE_EVENT_KIND_HORIZONTAL_WHEEL = 526,
	COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_DOUBLE_CLICK = 515,
	COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_DOWN = 513,
	COREWEBVIEW2_MOUSE_EVENT_KIND_LEFT_BUTTON_UP = 514,
	COREWEBVIEW2_MOUSE_EVENT_KIND_LEAVE = 675,
	COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_DOUBLE_CLICK = 521,
	COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_DOWN = 519,
	COREWEBVIEW2_MOUSE_EVENT_KIND_MIDDLE_BUTTON_UP = 520,
	COREWEBVIEW2_MOUSE_EVENT_KIND_MOVE = 512,
	COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_DOUBLE_CLICK = 518,
	COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_DOWN = 516,
	COREWEBVIEW2_MOUSE_EVENT_KIND_RIGHT_BUTTON_UP = 517,
	COREWEBVIEW2_MOUSE_EVENT_KIND_WHEEL = 522,
	COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_DOUBLE_CLICK = 525,
	COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_DOWN = 523,
	COREWEBVIEW2_MOUSE_EVENT_KIND_X_BUTTON_UP = 524
}
