using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_PDF_TOOLBAR_ITEMS")]
public enum COREWEBVIEW2_PDF_TOOLBAR_ITEMS
{
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_NONE = 0,
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE = 1,
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_PRINT = 2,
	COREWEBVIEW2_PDF_TOOLBAR_ITEMS_SAVE_AS = 4
}
