using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_PROCESS_FAILED_REASON")]
public enum COREWEBVIEW2_PROCESS_FAILED_REASON
{
	COREWEBVIEW2_PROCESS_FAILED_REASON_UNEXPECTED,
	COREWEBVIEW2_PROCESS_FAILED_REASON_UNRESPONSIVE,
	COREWEBVIEW2_PROCESS_FAILED_REASON_TERMINATED,
	COREWEBVIEW2_PROCESS_FAILED_REASON_CRASHED,
	COREWEBVIEW2_PROCESS_FAILED_REASON_LAUNCH_FAILED,
	COREWEBVIEW2_PROCESS_FAILED_REASON_OUT_OF_MEMORY
}
