using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_CLIENT_CERTIFICATE_KIND")]
public enum COREWEBVIEW2_CLIENT_CERTIFICATE_KIND
{
	COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_SMART_CARD,
	COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_PIN,
	COREWEBVIEW2_CLIENT_CERTIFICATE_KIND_OTHER
}
