using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_KEY_EVENT_KIND")]
public enum COREWEBVIEW2_KEY_EVENT_KIND
{
	COREWEBVIEW2_KEY_EVENT_KIND_KEY_DOWN,
	COREWEBVIEW2_KEY_EVENT_KIND_KEY_UP,
	COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_DOWN,
	COREWEBVIEW2_KEY_EVENT_KIND_SYSTEM_KEY_UP
}
