using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND")]
public enum COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND
{
	COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_COMMAND,
	COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_CHECK_BOX,
	COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_RADIO,
	COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_SEPARATOR,
	COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_SUBMENU
}
