using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Microsoft.Web.WebView2.Core.Raw;

[CompilerGenerated]
[TypeIdentifier("26D34152-879F-4065-BEA2-3DAA2CFADFB8", "Microsoft.Web.WebView2.Core.Raw.COREWEBVIEW2_POINTER_EVENT_KIND")]
public enum COREWEBVIEW2_POINTER_EVENT_KIND
{
	COREWEBVIEW2_POINTER_EVENT_KIND_ACTIVATE = 587,
	COREWEBVIEW2_POINTER_EVENT_KIND_DOWN = 582,
	COREWEBVIEW2_POINTER_EVENT_KIND_ENTER = 585,
	COREWEBVIEW2_POINTER_EVENT_KIND_LEAVE = 586,
	COREWEBVIEW2_POINTER_EVENT_KIND_UP = 583,
	COREWEBVIEW2_POINTER_EVENT_KIND_UPDATE = 581
}
