using System.Diagnostics.CodeAnalysis;

namespace ActiproSoftware.Products.SyntaxEditor;

public enum SRName
{
	ExAdornmentManagerConstructorNotFound,
	ExAdornmentManagerConstructorUnableToLoad,
	ExEditActionCannotRecord,
	ExExtensionMustBeSRExtension,
	ExInvalidCaretWidth,
	ExInvalidLanguageDefinitionStream,
	ExInvalidSelectionMode,
	ExInvalidStringResourceName,
	ExNoAllTabFilter,
	ExNoOutliningNodeDefinition,
	ExNoOutliningSourceDefinitionReturned,
	ExNoStringResource,
	ExOneAllTabFilter,
	ExOutliningSourceConstructorNotFound,
	ExOutliningSourceConstructorUnableToLoad,
	ExSessionAlreadyOpen,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Tagger")]
	ExTaggerConstructorNotFound,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Tagger")]
	ExTaggerConstructorUnableToLoad,
	ExTypeNotFound,
	ExUnableToRetrieveTextBoundsForOffset,
	ExValueGreaterThanZero,
	UIAmbientHighlightingStyleRegistryDescription,
	UIClassificationTypeBreakpointDisabled,
	UIClassificationTypeBreakpointEnabled,
	UIClassificationTypeCurrentStatement,
	UIClassificationTypeCodeSnippetDependentField,
	UIClassificationTypeCodeSnippetField,
	UIClassificationTypeCollapsedText,
	UIClassificationTypeCollapsibleRegion,
	UIClassificationTypeCurrentLine,
	UIClassificationTypeDelimiterMatching,
	UIClassificationTypeFindMatchHighlight,
	UIClassificationTypeFindScopeHighlight,
	UIClassificationTypeInactiveSelectedText,
	UIClassificationTypeIndentationGuides,
	UIClassificationTypeIndicatorMargin,
	UIClassificationTypeLineNumbers,
	UIClassificationTypeOutliningMarginSquare,
	UIClassificationTypeOutliningMarginVerticalRule,
	[SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "PlainText")]
	UIClassificationTypePlainText,
	UIClassificationTypeRevertedChangesMark,
	UIClassificationTypeSavedChangesMark,
	UIClassificationTypeSelectedText,
	UIClassificationTypeUnsavedChangesMark,
	[SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Whitespace")]
	UIClassificationTypeVisibleWhitespace,
	UICommandApplyDefaultOutliningExpansionText,
	UICommandBackspaceText,
	UICommandBackspaceToPreviousWordText,
	UICommandCancelMacroRecordingText,
	UICommandCapitalizeText,
	UICommandCodeBlockSelectionContractText,
	UICommandCodeBlockSelectionExpandText,
	UICommandCollapseSelectionText,
	UICommandCollapseSelectionLeftText,
	UICommandCollapseSelectionRightText,
	UICommandCollapseToDefinitionsText,
	UICommandCommentLinesText,
	UICommandConvertSpacesToTabsText,
	UICommandConvertTabsToSpacesText,
	UICommandCopyAndAppendToClipboardText,
	UICommandCopyToClipboardText,
	UICommandCutAndAppendToClipboardText,
	[SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "CutLine")]
	UICommandCutLineToClipboardText,
	UICommandCutToClipboardText,
	UICommandDeleteText,
	UICommandDeleteBlankLinesText,
	[SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Whitespace")]
	UICommandDeleteHorizontalWhitespaceText,
	UICommandDeleteLineText,
	UICommandDeleteToLineEndText,
	UICommandDeleteToLineStartText,
	UICommandDeleteToNextWordText,
	UICommandDuplicateText,
	UICommandExpandAllOutliningText,
	UICommandFindText,
	UICommandFindNextText,
	UICommandFindNextSelectedText,
	UICommandFindPreviousText,
	UICommandFindPreviousSelectedText,
	UICommandFormatDocumentText,
	UICommandFormatSelectionText,
	UICommandHideSelectionText,
	UICommandIncrementalSearchText,
	UICommandIndentText,
	UICommandInsertLineBreakText,
	UICommandInsertTabStopOrIndentText,
	UICommandMacroText,
	UICommandMakeLowercaseText,
	UICommandMakeUppercaseText,
	UICommandMoveDownText,
	UICommandMoveLeftText,
	UICommandMovePageDownText,
	UICommandMovePageUpText,
	UICommandMoveRightText,
	UICommandMoveSelectedLinesDownText,
	UICommandMoveSelectedLinesUpText,
	UICommandMoveToDocumentEndText,
	UICommandMoveToDocumentStartText,
	UICommandMoveToLineEndText,
	UICommandMoveToLineStartText,
	UICommandMoveToLineStartAfterIndentationText,
	UICommandMoveToMatchingBracketText,
	UICommandMoveToNextLineStartAfterIndentationText,
	UICommandMoveToNextWordText,
	UICommandMoveToPreviousLineStartAfterIndentationText,
	UICommandMoveToPreviousWordText,
	UICommandMoveToVisibleBottomText,
	UICommandMoveToVisibleTopText,
	UICommandMoveUpText,
	UICommandOpenLineAboveText,
	UICommandOpenLineBelowText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Outdent")]
	UICommandOutdentText,
	UICommandPasteFromClipboardText,
	UICommandPauseResumeMacroRecordingText,
	UICommandRedoText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Outdent")]
	UICommandRemoveTabStopOrOutdentText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Intelli")]
	UICommandRequestIntelliPromptAutoCompleteText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Intelli")]
	UICommandRequestIntelliPromptCompletionSessionText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Intelli")]
	UICommandRequestIntelliPromptInsertSnippetSessionText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Intelli")]
	UICommandRequestIntelliPromptParameterInfoSessionText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Intelli")]
	UICommandRequestIntelliPromptQuickInfoSessionText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Intelli")]
	UICommandRequestIntelliPromptSurroundWithSessionText,
	UICommandReplaceText,
	UICommandResetZoomLevelText,
	UICommandReverseIncrementalSearchText,
	UICommandRunMacroText,
	UICommandScrollDownText,
	UICommandScrollLeftText,
	UICommandScrollLineToVisibleBottomText,
	UICommandScrollLineToVisibleMiddleText,
	UICommandScrollLineToVisibleTopText,
	UICommandScrollPageDownText,
	UICommandScrollPageUpText,
	UICommandScrollRightText,
	UICommandScrollToDocumentEndText,
	UICommandScrollToDocumentStartText,
	UICommandScrollUpText,
	UICommandSelectAllText,
	UICommandSelectBlockDownText,
	UICommandSelectBlockLeftText,
	UICommandSelectBlockRightText,
	UICommandSelectBlockToNextWordText,
	UICommandSelectBlockToPreviousWordText,
	UICommandSelectBlockUpText,
	UICommandSelectDownText,
	UICommandSelectLeftText,
	UICommandSelectPageDownText,
	UICommandSelectPageUpText,
	UICommandSelectRightText,
	UICommandSelectToDocumentEndText,
	UICommandSelectToDocumentStartText,
	UICommandSelectToLineEndText,
	UICommandSelectToLineStartText,
	UICommandSelectToLineStartAfterIndentationText,
	UICommandSelectToMatchingBracketText,
	UICommandSelectToNextWordText,
	UICommandSelectToPreviousWordText,
	UICommandSelectToVisibleBottomText,
	UICommandSelectToVisibleTopText,
	UICommandSelectUpText,
	UICommandSelectWordText,
	UICommandStartAutomaticOutliningText,
	UICommandStopHidingCurrentText,
	UICommandStopOutliningText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Tabify")]
	UICommandTabifySelectedLinesText,
	UICommandToggleAllOutliningExpansionText,
	UICommandToggleCharacterCasingText,
	UICommandToggleMacroRecordingText,
	UICommandToggleOutliningExpansionText,
	UICommandToggleOverwriteModeText,
	UICommandTransposeCharactersText,
	UICommandTransposeLinesText,
	UICommandTransposeWordsText,
	[SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Whitespace")]
	UICommandTrimAllTrailingWhitespaceText,
	[SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Whitespace")]
	UICommandTrimTrailingWhitespaceText,
	UICommandUncommentLinesText,
	UICommandUndoText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Untabify")]
	UICommandUntabifySelectedLinesText,
	UICommandZoomInText,
	UICommandZoomOutText,
	UIEditorSearchScopeDocumentText,
	UIEditorSearchScopeSelectionText,
	UIEditorSearchViewFindAllButtonText,
	UIEditorSearchViewFindModeText,
	UIEditorSearchViewFindNextButtonText,
	UIEditorSearchViewFindOptionsExpanderHeaderText,
	UIEditorSearchViewFindWhatLabelText,
	UIEditorSearchViewMatchCaseCheckBoxText,
	UIEditorSearchViewMatchWholeWordCheckBoxText,
	UIEditorSearchViewReplaceAllButtonText,
	UIEditorSearchViewReplaceModeText,
	UIEditorSearchViewReplaceNextButtonText,
	UIEditorSearchViewReplaceWithLabelText,
	UIEditorSearchViewSearchHiddenTextCheckBoxText,
	UIEditorSearchViewSearchScopeLabelText,
	UIEditorSearchViewSearchTypeLabelText,
	UIEditorSearchViewSearchUpCheckBoxText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Intelli")]
	UIIntelliPromptCodeSnippetSelectorInsertSnippetText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Intelli")]
	UIIntelliPromptCodeSnippetSelectorSurroundWithText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Intelli")]
	UIIntelliPromptCompletionListNoItemsText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Intelli")]
	UIIntelliPromptPopupContentCodeSnippetShortcutPrefix,
	UIKeyAddText,
	UIKeyBackText,
	UIKeyD0Text,
	UIKeyD1Text,
	UIKeyD2Text,
	UIKeyD3Text,
	UIKeyD4Text,
	UIKeyD5Text,
	UIKeyD6Text,
	UIKeyD7Text,
	UIKeyD8Text,
	UIKeyD9Text,
	UIKeyDecimalText,
	UIKeyDeleteText,
	UIKeyDivideText,
	UIKeyDownText,
	UIKeyEscapeText,
	UIKeyInsertText,
	UIKeyLeftText,
	UIKeyLWinText,
	UIKeyMultiplyText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Num")]
	UIKeyNumPad0Text,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Num")]
	UIKeyNumPad1Text,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Num")]
	UIKeyNumPad2Text,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Num")]
	UIKeyNumPad3Text,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Num")]
	UIKeyNumPad4Text,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Num")]
	UIKeyNumPad5Text,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Num")]
	UIKeyNumPad6Text,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Num")]
	UIKeyNumPad7Text,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Num")]
	UIKeyNumPad8Text,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Num")]
	UIKeyNumPad9Text,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Oem")]
	UIKeyOemCloseBracketsText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Oem")]
	UIKeyOemCommaText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Oem")]
	UIKeyOemMinusText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Oem")]
	UIKeyOemOpenBracketsText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Oem")]
	UIKeyOemPeriodText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Oem")]
	UIKeyOemPipeText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Oem")]
	UIKeyOemPlusText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Oem")]
	UIKeyOemQuestionText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Oem")]
	UIKeyOemQuotesText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Oem")]
	UIKeyOemSemicolonText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Oem")]
	UIKeyOemTildeText,
	UIKeyPageDownText,
	UIKeyPageUpText,
	UIKeyPauseText,
	UIKeyReturnText,
	UIKeyRightText,
	UIKeyRWinText,
	UIKeySubtractText,
	UIKeyUpText,
	UIMenuItemCopyText,
	UIMenuItemCutText,
	UIMenuItemDeleteText,
	UIMenuItemPasteText,
	UIMenuItemSelectAllText,
	UIMenuItemRedoText,
	UIMenuItemUndoText,
	UIModifierKeysAltText,
	UIModifierKeysControlText,
	UIModifierKeysDelimiterText,
	UIModifierKeysShiftText,
	UIPrinterPageNumberText,
	UIPrinterPageNumberAndCountText,
	UIPrintPreviewWindowTitle,
	UISearchOverlayPaneCloseButtonToolTip,
	UISearchOverlayPaneFindAllButtonToolTip,
	UISearchOverlayPaneFindNextButtonToolTip,
	UISearchOverlayPaneFindWhatTextBoxPlaceholderText,
	UISearchOverlayPaneMatchCaseButtonToolTip,
	UISearchOverlayPaneMatchWholeWordButtonToolTip,
	UISearchOverlayPaneReplaceAllButtonToolTip,
	UISearchOverlayPaneReplaceNextButtonToolTip,
	UISearchOverlayPaneReplaceWithTextBoxPlaceholderText,
	UISearchOverlayPaneSearchUpButtonToolTip,
	UISearchOverlayPaneToggleReplaceButtonToolTip,
	UISearchOverlayPaneUseRegularExpressionsButtonToolTip
}
