using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Windows;
using System.Windows.Markup;

[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.RegexNode.#.ctor(System.Int32,System.String)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.RegexNode.#.ctor(System.Int32,ActiproSoftware.Windows.Controls.Editors.RegularExpressions.RegexNode)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.RegexHelper.#Escape(System.String)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.RegexHelper.#Escape(System.String,System.Boolean)")]
[assembly: AssemblyDescription("Advanced data entry editors for WPF.")]
[assembly: AssemblyConfiguration("")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.RegexNode.#GetPrefixCharacters(ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass)")]
[assembly: AssemblyTitle("Actipro Editors (for WPF)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.StringTextBufferReader.#Peek(System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ActiproSoftware.Windows.Themes")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Themes")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.MaskRegexParser.#ProcessAdvancedGroupingConstruct()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.MaskRegexParser.#ProcessSubstitution()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.InvalidRegexPatternException.#.ctor(System.String,System.Exception)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.MaskMatchResult.#InputText")]
[assembly: XmlnsPrefix("http://schemas.actiprosoftware.com/winfx/xaml/editors", "editors")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/editors", "ActiproSoftware.Products.Editors")]
[assembly: XmlnsPrefix("http://schemas.actiprosoftware.com/winfx/xaml/themes", "themes")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/themes", "ActiproSoftware.Windows.Themes")]
[assembly: AssemblyInformationalVersion("21.1.0.0")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/editors", "ActiproSoftware.Windows.Controls.Editors")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/editors", "ActiproSoftware.Windows.Controls.Editors.Primitives")]
[assembly: AssemblyCopyright("Copyright (c) 2009-2021 Actipro Software LLC.  All rights reserved.")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCompany("Actipro Software LLC")]
[assembly: AssemblyProduct("Editors")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: ThemeInfo(ResourceDictionaryLocation.None, ResourceDictionaryLocation.SourceAssembly)]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Controls.Editors.Primitives")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#.ctor(System.Char,System.Boolean)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#.ctor(System.Char,System.Char,System.Boolean)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#CharacterCount")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#.ctor(System.Char)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#.ctor(System.String)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#Contains(System.Char,System.Char)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#.ctor(ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#.ctor(ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharInterval[])")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#Alpha")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#CanMergeWith(ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharInterval.#IntersectsWith(ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharInterval)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#AddRange(ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharInterval[])")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#Contains(ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#RemoveCategory(System.Globalization.UnicodeCategory)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#Whitespace")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#Remove(System.Char)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#RemoveCategory(System.String)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Controls.Editors")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Controls.Editors.Automation.Peers")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharInterval.#Count")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharInterval.#GetIntersection(ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharInterval)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#LineTerminator")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#NonAlpha")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#HasCategorySpecification")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#HexDigit")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#NonLineTerminator")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#NonWhitespace")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#None")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Editors.RegularExpressions.CharClass.#NonHexDigit")]
[assembly: AssemblyVersion("21.1.0.0")]
