using System.Diagnostics.CodeAnalysis;

namespace ActiproSoftware.Products.Text;

public enum SRName
{
	[SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "AutoCorrect")]
	ExAutoCorrectNotPermittedWithRegex,
	ExEnumerationEnded,
	ExEnumerationNotStarted,
	ExIntervalsDoNotIntersect,
	ExInvalidDynamicLexicalMacroRegex,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Lexer")]
	ExInvalidDynamicLexerLexicalStateType,
	ExInvalidDynamicLexicalPatternGroupLookAheadRegex,
	ExInvalidDynamicLexicalPatternGroupLookBehindRegex,
	ExInvalidDynamicLexicalPatternGroupRegex,
	ExInvalidEncodedCharacter,
	ExInvalidMacroKey,
	ExInvalidOffsetLength,
	ExInvalidParameterType,
	ExInvalidRegexNodeType,
	[SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Op")]
	ExInvalidRegexOpCode,
	ExInvalidUnicodeCategoryName,
	ExInvalidWalkerTreeStateMovingToNextLeaf,
	ExInvalidWalkerTreeStateMovingToPreviousLeaf,
	ExNoDefaultLexicalState,
	ExNoFindText,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Lexer")]
	ExNoMergableLexer,
	ExNoMergableToken,
	ExParseRequestNoParser,
	ExReaderClosed,
	ExReadOnlyCollection,
	ExRegexParserEmptyQuotedString,
	ExRegexParserInvalidRangeCharacter,
	ExRegexParserInvalidSubstitutionGroupNumber,
	ExRegexParserNoLeftExpressionForBarOperand,
	ExRegexParserNoRangeMinimum,
	ExRegexParserNoRegularExpression,
	ExRegexParserOpenCurlyBraceExpected,
	ExRegexParserUnexpectedCharClassEnd,
	ExRegexParserUnexpectedGroupingConstructEnd,
	ExRegexParserUnexpectedLookBehindConstructEnd,
	ExRegexParserUnexpectedMacroReferenceEnd,
	ExRegexParserUnexpectedQuotedStringEnd,
	ExRegexParserUnexpectedRangeEnd,
	ExRegexParserUnknownGroupingConstruct,
	ExStartOffsetNotInSearchRange,
	ExTabSizeMinimum,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Tagger")]
	ExTaggerConstructorNotFound,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Tagger")]
	ExTaggerConstructorUnableToLoad,
	ExTextChangeOffsetDeltaSequentialOnlyInvalidOperation,
	ExTextChangeOperationRequired,
	ExTextChangeRequiresOneOperation,
	ExTextSnapshotRangeDeleted,
	ExTextSnapshotRangeSnapshotMismatch,
	ExTextSnapshotRequiresCodeDocument,
	ExTextSnapshotRequiresTextDocumentBase,
	ExTextVersionDocumentMismatch,
	UIClassificationTypeComment,
	UIClassificationTypeCompilerError,
	UIClassificationTypeIdentifier,
	UIClassificationTypeNumber,
	UIClassificationTypeKeyword,
	UIClassificationTypeOtherError,
	UIClassificationTypePreprocessorKeyword,
	UIClassificationTypeReadOnlyRegion,
	UIClassificationTypeString,
	UIClassificationTypeSyntaxError,
	UIClassificationTypeWarning,
	[SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "PlainText")]
	UILanguageKeyPlainText,
	UISearchOperationTypeFindAll,
	UISearchOperationTypeFindNext,
	UISearchOperationTypeReplaceAll,
	UISearchOperationTypeReplaceNext,
	UISearchPatternProviderAcronym,
	UISearchPatternProviderNormal,
	UISearchPatternProviderRegularExpression,
	UISearchPatternProviderShorthand,
	UISearchPatternProviderWildcard,
	UISearchResultWrapped,
	UITextChangeTypeAutoComplete,
	[SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "AutoCorrect")]
	UITextChangeTypeAutoCorrect,
	UITextChangeTypeAutoFormat,
	UITextChangeTypeAutoIndent,
	UITextChangeTypeAutoReplace,
	UITextChangeTypeBackspace,
	UITextChangeTypeChangeCase,
	UITextChangeTypeCommentLines,
	UITextChangeTypeConvertSpacesToTabs,
	UITextChangeTypeConvertTabsToSpaces,
	UITextChangeTypeCustom,
	UITextChangeTypeCut,
	UITextChangeTypeDelete,
	UITextChangeTypeDragAndDrop,
	UITextChangeTypeDuplicate,
	UITextChangeTypeEnter,
	UITextChangeTypeHeaderAndFooterChange,
	UITextChangeTypeIndent,
	UITextChangeTypeInsertCodeSnippetTemplate,
	UITextChangeTypeInsertFile,
	UITextChangeTypeMoveSelectedLinesDown,
	UITextChangeTypeMoveSelectedLinesUp,
	UITextChangeTypeOpenLine,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Outdent")]
	UITextChangeTypeOutdent,
	UITextChangeTypePaste,
	UITextChangeTypeReplace,
	UITextChangeTypeReplaceAll,
	UITextChangeTypeSpellingChange,
	UITextChangeTypeTextReplacement,
	UITextChangeTypeToggleCase,
	UITextChangeTypeTransposeCharacters,
	UITextChangeTypeTransposeLines,
	UITextChangeTypeTransposeWords,
	[SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Whitespace")]
	UITextChangeTypeTrimTrailingWhitespace,
	UITextChangeTypeTyping,
	UITextChangeTypeUncommentLines,
	UITextChangeTypeUpdateCodeSnippetTemplateFields,
	UITextStatisticAverageLettersPerWord,
	UITextStatisticAverageSyllablesPerWord,
	UITextStatisticAverageWordsPerSentence,
	UITextStatisticCharacters,
	UITextStatisticConsonants,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flesch")]
	UITextStatisticFleschKincaidGradeLevel,
	[SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Flesch")]
	UITextStatisticFleschReadingEaseScore,
	UITextStatisticLetters,
	UITextStatisticLines,
	[SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Whitespace")]
	UITextStatisticNonWhitespaceCharacters,
	[SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Whitespace")]
	UITextStatisticNonWhitespaceLines,
	UITextStatisticSentences,
	UITextStatisticSyllables,
	UITextStatisticVowels,
	UITextStatisticWords
}
