namespace ActiproSoftware.Text.RegularExpressions;

internal enum RegexOpCodeName
{
	Char = 1,
	NotChar = 2,
	CharClass = 3,
	String = 4,
	DocumentStart = 5,
	DocumentEnd = 6,
	LineStart = 7,
	LineEnd = 8,
	WordBoundary = 9,
	NonWordBoundary = 10,
	LazyBranch = 16,
	BranchMark = 17,
	NullCount = 18,
	SetCount = 19,
	BranchCount = 20,
	NullMark = 21,
	SetMark = 22,
	CaptureMark = 23,
	GetMark = 24,
	SetJump = 25,
	BackJump = 26,
	ForeJump = 27,
	GoTo = 28,
	Stop = 29,
	LeftToRight = 30,
	RightToLeft = 31,
	WordChar = 32,
	NonWordChar = 33,
	AllChar = 34,
	NoneChar = 35,
	AlphaChar = 36,
	NonAlphaChar = 37,
	DigitChar = 38,
	NonDigitChar = 39,
	HexDigitChar = 40,
	NonHexDigitChar = 41,
	WhitespaceChar = 42,
	NonWhitespaceChar = 43,
	LineTerminatorChar = 44,
	NonLineTerminatorChar = 45,
	LineTerminatorWhitespaceChar = 46,
	NonLineTerminatorWhitespaceChar = 47
}
