using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Windows;
using System.Windows.Markup;

[assembly: SuppressMessage("Microsoft.Usage", "CA1806:DoNotIgnoreMethodResults", MessageId = "ActiproSoftware.Windows.Interop.NativeMethods.SetWindowRgn(System.IntPtr,System.IntPtr,System.Boolean)", Scope = "member", Target = "ActiproSoftware.Windows.Interop.NativeMethods.#UpdateWindowClipRegion(System.IntPtr,System.Nullable`1<ActiproSoftware.Windows.Interop.NativeMethods+WINDOWPOS>,System.Windows.CornerRadius)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "TouchUp", Scope = "member", Target = "ActiproSoftware.Windows.Input.IInputTouchFrame.#SuspendMousePromotionUntilTouchUp()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "TouchUp", Scope = "member", Target = "ActiproSoftware.Windows.Input.IInputSource.#PreviewTouchUp")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Interop.NativeMethods.#ReleaseDC(System.IntPtr,System.IntPtr)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "logPixelsY", Scope = "member", Target = "ActiproSoftware.Windows.Interop.NativeMethods.#DeviceToLogicalTransform")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Interop.NativeMethods.#GetDC(System.IntPtr)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ActiproSoftware.Windows.Interop.NativeMethods.#GetDeviceCaps(System.IntPtr,ActiproSoftware.Windows.Interop.NativeMethods+DeviceCapItem)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Controls.Rendering")]
[assembly: SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Scope = "type", Target = "ActiproSoftware.Windows.Controls.Rendering.CanvasControl")]
[assembly: AssemblyTitle("Actipro Shared Library (for WPF)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Data.Filtering")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ActiproSoftware.Windows.Shapes")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Shapes")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "ActiproSoftware.Windows.Themes.WindowChromeManager.#ActiproSoftware.Windows.Interop.NativeMethods+IWindowChromeManager.HitTestNonClientArea(System.Windows.Rect,System.Windows.Point,System.Windows.Point)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "TintGroup", Scope = "member", Target = "ActiproSoftware.Windows.Themes.TintGroup.#Name")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "TintGroup", Scope = "member", Target = "ActiproSoftware.Windows.Themes.TintGroup.#TintColor")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "metadata", Scope = "member", Target = "ActiproSoftware.Windows.EnumerableView`1.#AddInternal(!0,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "ActiproSoftware.Windows.Themes.TintGroup.#NoTint")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "ActiproSoftware.Products.Shared.ThemesLogo.#Green")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "ActiproSoftware.Products.Shared.ThemesLogo.#Blue")]
[assembly: SuppressMessage("Microsoft.Portability", "CA1903:UseOnlyApiFromTargetedFramework", MessageId = "System.Windows.Controls.PasswordBox.#get_SecurePassword()", Scope = "member", Target = "ActiproSoftware.Windows.Controls.HintProperties.#SetHasContent(System.Windows.Controls.PasswordBox)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "hDC", Scope = "member", Target = "ActiproSoftware.Windows.Interop.NativeMethods.#DeviceToLogicalTransform")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "hWnd", Scope = "member", Target = "ActiproSoftware.Windows.Interop.NativeMethods.#DeviceToLogicalTransform")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "logPixelsX", Scope = "member", Target = "ActiproSoftware.Windows.Interop.NativeMethods.#DeviceToLogicalTransform")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "metadata", Scope = "member", Target = "ActiproSoftware.Windows.EnumerableView`1.#ReplaceInternal(System.Int32,!0,System.Boolean)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "metadata", Scope = "member", Target = "ActiproSoftware.Windows.EnumerableView`1.#MoveInternal(System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "metadata", Scope = "member", Target = "ActiproSoftware.Windows.EnumerableView`1.#ReevaluateAt(System.Int32)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "metadata", Scope = "member", Target = "ActiproSoftware.Windows.EnumerableView`1.#RemoveAtInternal(System.Int32,System.Int32)")]
[assembly: AssemblyDescription("Base classes for Actipro WPF products.")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/shared", "ActiproSoftware.Windows.Input")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/shared", "ActiproSoftware.Windows.DocumentManagement")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/shared", "ActiproSoftware.Windows.Media")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/shared", "ActiproSoftware.Windows.Data.Filtering")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/shared", "ActiproSoftware.Windows.Controls.Primitives")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/shared", "ActiproSoftware.Windows.Controls.Rendering")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/shared", "ActiproSoftware.Windows.Data")]
[assembly: AssemblyInformationalVersion("21.1.0.0")]
[assembly: InternalsVisibleTo("Views.Tests, PublicKey=0024000004800000940000000602000000240000525341310004000001000100cd030a14a47aab3d7bdafaa970d4b81f3e23ede5ccece89bf195ec44ba018463b8503df92d9f8c13ad9de265aa04c99876831acb7081c53ac26fd24235ddf9bd71cbc5a6790a6c0b871b4370c0521d185e793e3417834028a804c9cb71d3e114592d2cc4188a8afd1330556755ce8b336f18077408dee44542701633fe67a0b5")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/themes", "ActiproSoftware.Windows.Themes")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/shared", "ActiproSoftware.Windows.Media.Animation")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/shared", "ActiproSoftware.Windows.Shapes")]
[assembly: XmlnsPrefix("http://schemas.actiprosoftware.com/winfx/xaml/themes", "themes")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: AssemblyCopyright("Copyright (c) 2001-2021 Actipro Software LLC.  All rights reserved.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Actipro Software LLC")]
[assembly: AssemblyProduct("Shared")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/shared", "ActiproSoftware.Windows")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/shared", "ActiproSoftware.Windows.Controls")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/shared", "ActiproSoftware.Windows.Controls.ColorSelection")]
[assembly: XmlnsDefinition("http://schemas.actiprosoftware.com/winfx/xaml/shared", "ActiproSoftware.Products.Shared")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: ThemeInfo(ResourceDictionaryLocation.None, ResourceDictionaryLocation.SourceAssembly)]
[assembly: XmlnsPrefix("http://schemas.actiprosoftware.com/winfx/xaml/shared", "shared")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "ActiproSoftware.Products.Shared.ThemesLogo.#Palette")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Controls")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Controls.Automation.Peers")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Controls.Calendar")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Compatibility")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Products")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Products.Shared")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Data")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.DocumentManagement")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Extensions")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Input")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Controls.ColorSelection")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Controls.ColorSelection.Primitives")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Controls.Primitives")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ActiproSoftware.Compatibility")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ActiproSoftware.Products.Shared")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ActiproSoftware.Windows.Controls.Automation.Peers")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ActiproSoftware.Windows.Serialization")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "XamlGeneratedNamespace")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ActiproSoftware.Windows.Extensions")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ActiproSoftware.Windows.Controls.ColorSelection")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ActiproSoftware.Windows.Controls.ColorSelection.Primitives")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ActiproSoftware.Windows.Controls.Primitives")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Media")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.MessageBox.Show(System.String,System.String,System.Windows.MessageBoxButton,System.Windows.MessageBoxImage)", Scope = "member", Target = "ActiproSoftware.Products.LicenseWindow.#licenseTypeHyperLink_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Clipboard.SetText(System.String)", Scope = "member", Target = "ActiproSoftware.Products.LicenseWindow.#copyToClipboardButton_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.MessageBox.Show(System.String,System.String,System.Windows.MessageBoxButton)", Scope = "member", Target = "ActiproSoftware.Products.LicenseWindow.#checkForUpdateHyperLink_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Documents.Run.#ctor(System.String)", Scope = "member", Target = "ActiproSoftware.Products.LicenseWindow.#.ctor(ActiproSoftware.Products.ActiproLicense)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "AnimatedProgressBar", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Automation.Peers.AnimatedProgressBarAutomationPeer.#System.Windows.Automation.Provider.IValueProvider.SetValue(System.String)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Controls.TextBox.set_Text(System.String)", Scope = "member", Target = "ActiproSoftware.Products.LicenseWindow.#.ctor(ActiproSoftware.Products.ActiproLicense)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Controls.TextBlock.set_Text(System.String)", Scope = "member", Target = "ActiproSoftware.Products.LicenseWindow.#.ctor(ActiproSoftware.Products.ActiproLicense)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope = "member", Target = "ActiproSoftware.Products.Shared.ThemesLogo.#System.Windows.Markup.IComponentConnector.Connect(System.Int32,System.Object)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "ActiproSoftware.Products.Shared.ThemesLogo.#Yellow")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "ActiproSoftware.Products.Shared.ThemesLogo.#Red")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "ActiproSoftware.Windows.Themes.ThemeCatalogRegistrarBase`1")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.MessageBox.Show(System.String,System.String)", Scope = "member", Target = "ActiproSoftware.Products.LicenseWindow.#checkForUpdateHyperLink_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "System.Windows.Controls.TextBlock.set_Text(System.String)", Scope = "member", Target = "ActiproSoftware.Products.LicenseAdornerPopup.#.ctor(ActiproSoftware.Products.ActiproLicense)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "ActiproSoftware.Windows.Themes.SharedThemeCatalogRegistrar")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope = "member", Target = "ActiproSoftware.Products.LicenseWindow.#System.Windows.Markup.IComponentConnector.Connect(System.Int32,System.Object)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope = "member", Target = "ActiproSoftware.Products.LicenseAdornerPopup.#System.Windows.Markup.IComponentConnector.Connect(System.Int32,System.Object)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "ActiproSoftware.Products.LicenseWindow.#Polygon1Storyboard")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Shared", Scope = "namespace", Target = "ActiproSoftware.Products.Shared")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Media.Animation")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Serialization")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Actipro", Scope = "namespace", Target = "ActiproSoftware.Windows.Themes")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "XamlGeneratedNamespace.GeneratedInternalTypeHelper.#CreateDelegate(System.Type,System.Object,System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "XamlGeneratedNamespace.GeneratedInternalTypeHelper.#AddEventHandler(System.Reflection.EventInfo,System.Object,System.Delegate)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "AnimatedProgressBar", Scope = "member", Target = "ActiproSoftware.Windows.Controls.Automation.Peers.AnimatedProgressBarAutomationPeer.#System.Windows.Automation.Provider.IRangeValueProvider.SetValue(System.Double)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "XamlGeneratedNamespace.GeneratedInternalTypeHelper.#GetPropertyValue(System.Reflection.PropertyInfo,System.Object,System.Globalization.CultureInfo)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "ActiproSoftware.Products.LicenseWindow.#Polygon2Storyboard")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "ActiproSoftware.Products.LicenseWindow.#System.Windows.Markup.IComponentConnector.Connect(System.Int32,System.Object)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "XamlGeneratedNamespace.GeneratedInternalTypeHelper.#SetPropertyValue(System.Reflection.PropertyInfo,System.Object,System.Object,System.Globalization.CultureInfo)")]
[assembly: AssemblyVersion("21.1.0.0")]
